### ISSUE TITLE
ROADMAP

### ISSUE THREAD

**Issue by ptmt** [skeletcode/skelet#1]
## Improve tests & infrastructure
- [ ] Add eslint [and jscs];
- [ ] Add oslint or an alternative for linting objc;
- [ ] Add tests for javascript source code;
- [ ] Add objc unit tests;
- [ ] Add e2e tests;
## Common js app tasks
- [ ] Extract from styles all constants related to themes: colors, fonts, etc.;
- [ ] `.editorconfig` support;
- [ ] `.gitignore` support;
- [ ] File and replace in file;
- [ ] File and replace across working directory. 
- [ ] cmd + p (universal command spotlight)
## Improve TextView:
- [ ] onSelectionChange + Line / column indicator;;
- [ ] add auto focusing to TextView;
- [ ] Autocomplete support (language specific implementation move to plugin);
- [ ] Go-to-declaration support (language specific implementation move to plugin); 
- [ ] Comment / uncomment feature via cmd+/;
- [ ] Shifting tab / cmd + tab;
- [ ] Extract SKTextView as a stand-alone project, adding support for ios; 
## Filesystem Manager
- [ ] File saving;
## React plugin
- [ ] Tree debugging;
